layout_spectrum: 0.7740303
color:
  saturation: 0.7782462
  brandStrength: 1
  lightness: 0.2175379
  brandColors:
    - '#020228'
    - '#273667'
    - '#7D7C90'
    - '#436092'
    - '#F6E7E6'
  rhythmicContrast: 0.7774031
typography_spectrum: 1
name: Seditionists
