name: Seditionists
favicon: null
layout_spectrum: 0.7740303
typography_spectrum: 1
title: The Seditionists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010400'
    - '#ffffff'
    - '#cc3202'
    - '#f3b893'
    - '#524c44'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
