name: The Seditionists
favicon: null
layout_spectrum: 0.7740303
typography_spectrum: 1
title: Seditionists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000519'
    - '#551813'
    - '#55638a'
    - '#8a90b4'
    - '#fbfeff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
